compatibility_date = "2023-10-01"
# wrangler.toml
name = 'zjtm-worker'
main = "src/index.js"
# KV命名空间绑定
[[kv_namespaces]]
binding = "MODS_STORE"
id = "0e80c6b5e1b6469f8fa530ba8a657ed1"  # 替换为实际的KV命名空间ID

[[kv_namespaces]]
binding = "IMAGES_STORE"
id = "74b630f31a7f421fa603dcec95c8178d"  # 替换为实际的图片KV命名空间ID

# 变量配置
[vars]
ADMIN_TOKEN = "zjtmNB666"  # 替换为实际的管理员令牌
